# Generated by Django 4.1.7 on 2023-03-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_product_mrp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
